name: Deploy to github pages
on:
  push:
    branches:
      - master
jobs:
  gh-pages-deploy:
    name: Deploying to gh-pages
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v1.1.0
        with:
          version:  14.x
          env:
            ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

      - name: Checkout branch
        uses: actions/checkout@v2
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'


      - name: Clean install dependencies
        run: npm ci
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'


      - name: Run deploy script
        run: |
          git config user.name "KonstantinBiryukov" && git config user.email "kostya-leon@mail.ru"
          npm run gh-pages-deploy
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

